# Generated by Django 3.1.5 on 2021-01-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('serve_address', models.CharField(max_length=200)),
                ('serve_domain', models.CharField(max_length=200)),
                ('serve_port', models.IntegerField()),
                ('serve_path', models.CharField(max_length=1000)),
                ('last_start_time', models.DateTimeField(blank=True, null=True)),
                ('last_stop_time', models.DateTimeField(blank=True, null=True)),
                ('last_opera_user', models.CharField(default='root', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
